apiVersion: v1
kind: Namespace
metadata:
  name: trilog-system
  labels:
    name: trilog-system
    app.kubernetes.io/name: trilog
    app.kubernetes.io/part-of: trilog
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
