apiVersion: v1
kind: Service
metadata:
  name: nexus-state
  namespace: nexus-python
  labels:
    app: nexus-state
    component: backend
spec:
  type: NodePort
  selector:
    app: nexus-state
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30092
    protocol: TCP
    name: http
