apiVersion: v1
kind: Service
metadata:
  name: graphstudio-backend
  namespace: nexus-python
  labels:
    app: graphstudio-backend
    component: auth-service
spec:
  type: NodePort
  selector:
    app: graphstudio-backend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30090
    protocol: TCP
    name: http
