apiVersion: v1
kind: Service
metadata:
  name: graphstudio-frontend
  namespace: nexus-python
  labels:
    app: graphstudio-frontend
    component: frontend
spec:
  type: NodePort
  selector:
    app: graphstudio-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
